### PR TITLE
chore: comprehensively cleans up the `users` package and separates th…

### PR DESCRIPTION
**Pull request by jekutzsche**
…e responsibilities of `users` and `auth.db`

### CODE REVIEW

**Comment by mad-nuts** [comment]
@jekutzsche looks fine to me. I'll aprove it as soon as the conflict is resolved.

**Comment by jekutzsche** [comment]
Thank you for the positive feedback. I'll fix the conflict with rebase to develop once the previous PR is merged.

**Review by mad-nuts — APPROVED** [review]

**Review by lucky-lusa — APPROVED** [review]
Interesting approach to bring the dtos together. Looks good to me.

**Comment by jekutzsche** [comment]
Thanks for your reviews.

**Pull request merged**
