### PR TITLE
fix: adds grpc server to ga eps. still not reachable from outside, bu…

### PR DESCRIPTION
**Pull request by lucky-lusa**
…t necessary.

### CODE REVIEW

**Review by jekutzsche — DISMISSED** [review]
Should the changes still be taken somewhere for development environments?

**Comment by lucky-lusa** [comment]
I think locally this makes little sense for development, since we have no proxies on our machines and are not connected to the official dev-environment from our machines.

A complete environment would be necessary to be able to test purely locally in a meaningful way.

**Review by jekutzsche — APPROVED** [review]

**Pull request merged**
