### PR TITLE
feat: improved dates configuration for new events

### PR DESCRIPTION
**Pull request by faversente**
Some improvements regarding the date and time selection fields when creating new events:

- Selected start date can not be > "today"
- If selected start date = "today", selectable time is set to "now" and max. selectable time is also "now"
- Once start date+time is selected, end date is set to end of day (23:59) of start day. Changes if start date is changed afterwards
- For end date, no date previous than "start day" (if selected) can be selected, but there is no min. time restriction

All previous validations are still enabled

Refs: iris-connect/iris-backlog#117
Refs: iris-connect/iris-backlog#118

### CODE REVIEW

**Review by SWlionmint — CHANGES_REQUESTED** [review]
I have tested the implementation. It does work well on the UI.
There are a few problems:

- As far as I can tell when you change the start date and than automatically set the end date, only the start date is actually saved into the dataset. To check this I used a console output of dateString in setDateTime in date-time-input-field. Without this the data should not be available when sending the request out.
- There is some interaction if I first set a start date, than delete it. The result is that you can't set a end date. Don't know if that is the wanted result. It make sense with regard the next point.
- If you first set end date and than start date the end date is overwritten. We may want to restrict this to only happen when the new min and max are violated. Though as most events should only take a few hours it should not be a problem and might even be better.
- You can still set the date and time via keyboard, but this does not reset the end date in case you change the start date. Also the restrictions are not affected and as such you can set any date and time you want per keyboard.

**Comment by faversente** [comment]
> 
> 
> I have tested the implementation. It does work well on the UI.
> There are a few problems:
> 
>     * As far as I can tell when you change the start date and than automatically set the end date, only the start date is actually saved into the dataset. To check this I used a console output of dateString in setDateTime in date-time-input-field. Without this the data should not be available when sending the request out.
> 
>     * There is some interaction if I first set a start date, than delete it. The result is that you can't set a end date. Don't know if that is the wanted result. It make sense with regard the next point.
> 
>     * If you first set end date and than start date the end date is overwritten. We may want to restrict this to only happen when the new min and max are violated. Though as most events should only take a few hours it should not be a problem and might even be better.
> 
>     * You can still set the date and time via keyboard, but this does not reset the end date in case you change the start date. Also the restrictions are not affected and as such you can set any date and time you want per keyboard.

Thank you for the review and reply!

* In order to verify, I put a console log of the payload in the `submit()` method. I submitted a new event by selecting just the start date and not touching the end date. This is the output of the log:

grafik

`end` seems to be set correctly.

* I think it does not really matter, as as of the next point, end date is overwritten once start date ist set.

* I also think it isn't a problem. If a user needs to adjust the date, it probably means the end date has to be set adjusted to the same date, too. Maybe @stefanmichalk or @t0bska can give some input how the correct behavior should be.

* I tried with Chrome and Firefox and it works as intended (setting end date automatically and with validation) using the keyboard. BUT there seems to be no validation on start date at all, therefore you are right, you could put a date in the future for the start date. I'm going to put validation on start field as well.

**Comment by faversente** [comment]
@SWlionmint I added start date validation with latest commit. Please see comment above and re-review. Thanks!

**Comment by faversente** [comment]
@SWlionmint issue "1" of your comment above should be solved now.

**Review by SWlionmint — APPROVED** [review]
I have checked the changes and am happy with the result as such I think we can use it as it is.

**Pull request merged**
