### PR TITLE
feat: logo change and logos in 'about' page

### PR DESCRIPTION
**Pull request by faversente**
The IRIS logo was replaced with the new IRIS connect logo.

Logos of InÖg and BSS were added to the 'about' page.

Refs: iris-connect/iris-backlog#115
Refs: iris-connect/iris-backlog#112

### CODE REVIEW

**Comment by SWlionmint** [comment]
Da noch niemand gereviewed hat und ich gerade mehrere Merges gemacht habe, habe ich das von development mal rein gemerged. Gab keine Konflikte.

**Review by SWlionmint — COMMENTED** [review]
I have verified the code and can approve it with one exception. The firefox browser is not displaying the svg logos on the about page. It works in Chrome and Safari. If that is okay than I will approve, but perhaps you can check if you can fix that, as it does look better with the logos displayed.

**Comment by faversente** [comment]
> 
> 
> I have verified the code and can approve it with one exception. The firefox browser is not displaying the svg logos on the about page. It works in Chrome and Safari. If that is okay than I will approve, but perhaps you can check if you can fix that, as it does look better with the logos displayed.

Thanks for noticing! Didn't test with Firefox, therefore I didn't see it. 
Firefox requires the width to be provided. It is fixed with the latest commit.

**Review by SWlionmint — APPROVED** [review]
Works on firefox as well

**Pull request merged**
